### ISSUE TITLE
Reset / Teardown

### ISSUE THREAD

**Issue by onedr0p** [alexellis/k3sup#106]
Having a command to reset all the hosts to reinstall k3s would be nice, maybe a `--reset` flag would be cool to wipe and reset the node.

**Comment by alexellis** [comment]
Walk me through your use case? What is it that you're trying to achieve and how could k3sup help with that?

**Comment by onedr0p** [comment]
I am rapidly testing setting up and destroying k3s, and to reset my k3s nodes I currently wipe my sd card on my PI and reflash the OS. It would be nice to instead have ks3up reset my nodes, maybe a k3sdown tool ha.

**Comment by onedr0p** [comment]
Maybe you can have a command the executes

```
sudo /usr/local/bin/k3s-killall.sh
```

on the host?

**Comment by alexellis** [comment]
OK thanks for clarifying, Is there a different file for server and agent? (there was last time I checked)

I'd be fine with you submitting a PR for `k3sup uninstall --ip`. When could you work on it?

**Comment by onedr0p** [comment]
I thought the path was the same, but I'll double check and hopefully get a PR opened before the holiday season. Thanks for the feedback!

**Comment by cdata** [comment]
I think a reset/teardown step would be nice (probably also for "apps" as well). But FWIW it was pretty straight forward to automate teardown with an ansible playbook:

```yaml
---
- hosts: "*"
  tasks:
    - name: "Run k3s-killall.sh"
      become: yes
      command: k3s-killall.sh
    - name: "Run k3s-uninstall.sh"
      become: yes
      command:
        cmd: k3s-uninstall.sh
        removes: /usr/local/bin/k3s-uninstall.sh
    - name: "Run k3s-agent-uninstall.sh"
      become: yes
      command:
        cmd: k3s-agent-uninstall.sh
        removes: /usr/local/bin/k3s-agent-uninstall.sh
```
