### ISSUE TITLE
[Feature] Bootstrapping the whole cluster with single command

### ISSUE THREAD

**Issue by jnummelin** [alexellis/k3sup#152]
## Expected Behaviour

Currently `k3sup` requires user to bootstrap the server first and then join nodes separately. Would something like this make sense:
```
$ terraform output -json | yq r - k3s_cluster.value > cluster.yml && k3sup cluster --config cluster.yml 
$ #wait for ~2mins
$ kubectl get node
--> cluster online
```

In this example the `cluster.yml` file could look something like:
```
server:
  ip: 95.217.129.189
  user: root
workers:
- ip: 95.217.129.185
  user: root
- ip: 95.217.129.139
  user: root
- ip: 95.216.210.52
  user: root
```
(of course it should support all the options `k3sup install` and `k3sup join` supports)

As in the example command, this sort of approach would make working with terraform based infrastructure a breeze.

**Note:** I've got a super rough prototype of this mostly working, just wanted to see if this in general would be something that might get accepted into `k3sup` directly.

## Current Behaviour

User needs to run a command per node, either `k3sup install` or `k3sup join` depending on the node role.

## Possible Solution

Have a cluster config file that can easily be used to describe the whole cluster and the a command like `k3sup cluster --config cluster.yml` to bootstrap the whole cluster at once.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* What OS or type or VM are you using? Where is it hosted?

* Operating System and version (e.g. Linux, Windows, MacOS):
