### ISSUE TITLE
Add support to change context name on kubeconfig

### ISSUE THREAD

**Issue by blackjid** [alexellis/k3sup#39]
I would love to be able to define the name of the context created in the `kubeconfig` file.

I have something already working, but in the PR template says that I should open an issue first to comment and discuss the functionality.

## Current Behaviour
Today the generated `kubeconfig` file looks like this

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: https://<redacted>:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: <redacted>
    username: admin
```

## Possible Solution
I would love to be able to define something different to `default` on the values for all the values related to `cluster`, `user` and `context`

Something like this:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: https://<redacted>:6443
  name: homelab
contexts:
- context:
    cluster: homelab
    user: homelab
  name: homelab
current-context: homelab
kind: Config
preferences: {}
users:
- name: homelab
  user:
    password: <redacted>
    username: admin
```

## Context
- Be able to install several k3s clusters with k3sup from the same computer and merge all to the `$HOME/.kube/config` file without conflicts
- Have a more meaningful name when changing contexts
